// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiMxlmxIvMcrW1XOSwhgp4aQIV7vLkboY',
    appId: '1:348969314028:web:57a6865d08c32edb0667c9',
    messagingSenderId: '348969314028',
    projectId: 'storetest-b64f2',
    authDomain: 'storetest-b64f2.firebaseapp.com',
    storageBucket: 'storetest-b64f2.firebasestorage.app',
    measurementId: 'G-7G9BN75M2M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiwCV0aFuBfQMpN3EYVbztfnfG0xp5rUA',
    appId: '1:348969314028:android:4bfda5ac20b30bb00667c9',
    messagingSenderId: '348969314028',
    projectId: 'storetest-b64f2',
    storageBucket: 'storetest-b64f2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAn4isO7R-jWiJM-FeeTWxspp4dcWERelI',
    appId: '1:348969314028:ios:ca75e3ddfce71e440667c9',
    messagingSenderId: '348969314028',
    projectId: 'storetest-b64f2',
    storageBucket: 'storetest-b64f2.firebasestorage.app',
    androidClientId: '348969314028-1k4ffcfo7d7h4qu87cq9r2tdka90q3ni.apps.googleusercontent.com',
    iosClientId: '348969314028-9jjo7afre2qdh7v0ckk7181lsfql5huo.apps.googleusercontent.com',
    iosBundleId: 'com.example.storeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAn4isO7R-jWiJM-FeeTWxspp4dcWERelI',
    appId: '1:348969314028:ios:ca75e3ddfce71e440667c9',
    messagingSenderId: '348969314028',
    projectId: 'storetest-b64f2',
    storageBucket: 'storetest-b64f2.firebasestorage.app',
    iosBundleId: 'com.example.storeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiMxlmxIvMcrW1XOSwhgp4aQIV7vLkboY',
    appId: '1:348969314028:web:03ba8d776d12e09c0667c9',
    messagingSenderId: '348969314028',
    projectId: 'storetest-b64f2',
    authDomain: 'storetest-b64f2.firebaseapp.com',
    storageBucket: 'storetest-b64f2.firebasestorage.app',
    measurementId: 'G-VXYNFWB3B3',
  );
}